enable-module-update = false
parallel-jobs = 1

[LINE-Andrew]
app-name = "LINE"
patches-source = "andrewliang25/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Andrew"
build-mode = "module"
version = "26.11.0"
arch = "arm64-v8a"
include-stock = "auto"
exclusive-patches = true
included-patches = """\
  'Hide ad views' \
  'Remove banner ads' \
  'Hide Home modules' \
  'Disable VOOM' \
  'Hide VOOM tab' \
  """
archive-dlurl = "https://archive.org/download/andrews-apks/apks/jp.naver.line.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/line-corporation/line"
uptodown-dlurl = "https://line.en.uptodown.com/android"
